Minor documentation adjustments

diff --git a/bin/adminer b/bin/adminer
--- a/bin/adminer
+++ b/bin/adminer
@@ -32,7 +32,7 @@ while [ "$#" -gt 0 ]; do
 		-v|--verbose) verbose=1 ;;
 		-p=*|--port=*) port="${1#*=}" ;;
 		-h|--help) echo "$usage" && exit 0 ;;
-		*) echo "[x] Invalid command line flag $1" >&2; exit 1 ;;
+		*) echo "[x] Invalid command line flag $1." >&2; exit 1 ;;
 	esac
 	shift
 done
diff --git a/bin/mbx-upgrade b/bin/mbx-upgrade
--- a/bin/mbx-upgrade
+++ b/bin/mbx-upgrade
@@ -2,7 +2,7 @@
 
 read -r -d '' usage << EOF
 Usage: $(basename "$0") [OPTIONS]
-Upgrades Martin Braun's eXtensive toolkit.
+Upgrades Martin Braun's eXtensive toolbox.
 
 OPTIONS
   -V,   --version                 Prints the version of this script suite (MBX).
@@ -15,7 +15,7 @@ while [ "$#" -gt 0 ]; do
 		-V|--version) echo $MBX_VERSION && exit 0 ;;
 		-v|--verbose) verbose=1 ;;
 		-h|--help) echo "$usage" && exit 0 ;;
-		*) echo "[x] Invalid command line flag $1" >&2; exit 1 ;;
+		*) echo "[x] Invalid command line flag $1." >&2; exit 1 ;;
 	esac
 	shift
 done
diff --git a/bin/sys-backup b/bin/sys-backup
--- a/bin/sys-backup
+++ b/bin/sys-backup
@@ -6,6 +6,7 @@
 read -r -d '' usage << EOF
 Usage: $(basename "$0") [OPTIONS]
 Backups all files given a certain maximum size from the root directory of this system.
+On MacOS launch Time Maschine backup instead.
 
 OPTIONS
   -V,   --version                 Prints the version of this script suite (MBX).
@@ -29,7 +30,7 @@ while [ "$#" -gt 0 ]; do
 		-k|--keep-files) keep_files=1 ;;
 		-s|--shutdown) shutdown=1 ;;
 		-h|--help) echo "$usage" && exit 0 ;;
-		*) echo "[x] Invalid command line flag $1" >&2; exit 1 ;;
+		*) echo "[x] Invalid command line flag $1." >&2; exit 1 ;;
 	esac
 	shift
 done
@@ -41,6 +42,8 @@ if [[ "$(to-lower "$OSTYPE")" == "darwin"* ]]; then # MacOS uses Time Maschine f
 	echo "[o] Backing up using Time Maschine ..."
 	if (( $shutdown )); then
 		sudo zsh -c "tmutil startbackup --block && shutdown -h +5"
+		echo; read -rsn1 -p "Press any key to cancel ..."; echo
+		sudo killall shutdown
 	else
 		tmutil startbackup
 	fi
@@ -87,8 +90,12 @@ fi
 if (( $shutdown )); then
 	if test-command sudo; then
 		sudo shutdown +5
+		echo; read -rsn1 -p "Press any key to cancel ..."; echo
+		sudo killall shutdown
 	else
 		shutdown +5
+		echo; read -rsn1 -p "Press any key to cancel ..."; echo
+		killall shutdown
 	fi	
 fi
 
diff --git a/bin/sys-upgrade b/bin/sys-upgrade
--- a/bin/sys-upgrade
+++ b/bin/sys-upgrade
@@ -4,22 +4,28 @@
 
 read -r -d '' usage << EOF
 Usage: $(basename "$0") [OPTIONS]
-Upgrades the entire system, but the MBX toolkit. (Run mbx-upgrade for this)
+Upgrades all packages of all supported package managers. Supports:
+
+- apt-get
+- brew
+- gem
+- npm / nvm
+- flutter / fvm
 
 OPTIONS
   -V,   --version                 Prints the version of this script suite (MBX).
   -v,   --verbose                 Prints verbose information.
-  -h,   --help                    Prints this help message.
   -r,   --reboot                  Reboots the system after successful upgrade.
+  -h,   --help                    Prints this help message.
 EOF
 
 while [ "$#" -gt 0 ]; do
 	case "$1" in
 		-V|--version) echo $MBX_VERSION && exit 0 ;;
 		-v|--verbose) verbose=1 ;;
-		-h|--help) echo "$usage" && exit 0 ;;
 		-r|--reboot) reboot=1 ;;
-		*) echo "[x] Invalid command line flag $1" >&2; exit 1 ;;
+		-h|--help) echo "$usage" && exit 0 ;;
+		*) echo "[x] Invalid command line flag $1." >&2; exit 1 ;;
 	esac
 	shift
 done
