Improved error handling and restrict sys-backup

diff --git a/bin/chmodr b/bin/chmodr
--- a/bin/chmodr
+++ b/bin/chmodr
@@ -54,7 +54,7 @@ while [ "$#" -gt 0 ]; do
 		-c|--claim-ownership) claim_ownership=1 ;;
 		-s|--slow-mode) terminator=\; ;;
 		-h|--help) echo "$usage" && exit 0 ;;
-		*) { test -z $path && path=$1; } || { echo "Invalid command line flag $1" >&2 && exit 1; } ;;
+		*) { test -z $path && path=$1; } || { echo "[x] Invalid command line flag $1" >&2; exit 1; } ;;
 	esac
 	shift
 done
diff --git a/bin/sys-backup b/bin/sys-backup
--- a/bin/sys-backup
+++ b/bin/sys-backup
@@ -12,6 +12,7 @@ OPTIONS
   -v,   --verbose                 Prints verbose information.
   -p=*, --path=*                  Sets the path to the backup directory (default: $HOME/.sys-backup).
   -m=*, --max-size=*              Sets the maximum size of every backuped file (default: 10M).
+	-f,   --force                   Causes the backup to be performed even when it is not recommend.
   -k,   --keep-files              Keeps the old backup files that are not overwritten.
   -h,   --help                    Prints this help message.
 EOF
@@ -25,15 +26,21 @@ while [ "$#" -gt 0 ]; do
 		-v|--verbose) verbose=1 ;;
 		-p=*|--path=*) path="${1#*=}" ;;
 		-m=*|--max-size=*) max_size="${1#*=}" ;;
+		-f|--force) force=1 ;;
 		-k|--keep-files) keep_files=1 ;;
 		-h|--help) echo "$usage" && exit 0 ;;
-		*) echo "Invalid command line flag $1" >&2 && exit 1 ;;
+		*) echo "[x] Invalid command line flag $1" >&2; exit 1 ;;
 	esac
 	shift
 done
 
 test $verbose && trap 'echo "[o] $BASH_COMMAND"' DEBUG
 set -e
+
+if [[ "$(to-lower "$OSTYPE")" == "darwin"* && ! $force ]]; then # MacOS without force mode
+	echo "[x] Backups on MacOS should be made using time maschine." >&2
+	exit 1
+fi
 
 echo "[o] Creating backup directory ..."
 mkdir -p "$path"
diff --git a/bin/sys-upgrade b/bin/sys-upgrade
--- a/bin/sys-upgrade
+++ b/bin/sys-upgrade
@@ -17,7 +17,7 @@ while [ "$#" -gt 0 ]; do
 		-V|--version) echo $MBX_VERSION && exit 0 ;;
 		-v|--verbose) verbose=1 ;;
 		-h|--help) echo "$usage" && exit 0 ;;
-		*) echo "Invalid command line flag $1" >&2 && exit 1 ;;
+		*) echo "[x] Invalid command line flag $1" >&2; exit 1 ;;
 	esac
 	shift
 done
