feat(git-src): up all

diff --git a/bin/git-src b/bin/git-src
--- a/bin/git-src
+++ b/bin/git-src
@@ -1,6 +1,7 @@
 #!/usr/bin/env sh
 export LC_ALL=C
 
+# shellcheck disable=SC1091
 . "$MBX_LIBPATH/_.sh" || exit 1
 
 usage="$(cat << EOF
@@ -16,10 +17,11 @@ COMMAND
   sh                              Switches to the given repository/branch in a new shell.
   add                             Clones the given repository/branch with all its submodules with depth of 1 into the localized source storage.
   up                              Resets and pulls the latest changes on the given repository/branch.
+  up-all                          Resets and pulls the latest changes on all repositories/branches.
   del                             Deletes the given repository/branch from the system.
 
 REPO
-  Unused on the ls-command.
+  Unused on the ls and up-all command.
   For the add-command, needs to be a HTTPS URL or SSH destination ending with .git.
   For any other command it can also be just the sub path (without branch) on the file system.
 
@@ -37,7 +39,7 @@ path="/usr/local/src/git"
 
 while [ "$#" -gt 0 ]; do
 	case "$1" in
-		-V|--version) echo $MBX_VERSION && exit 0 ;;
+		-V|--version) echo "$MBX_VERSION" && exit 0 ;;
 		-v|--verbose) verbose=1 ;;
 		-p=*|--path=*) path="${1#*=}" ;;
 		-b=*|--branch=*) branch="${1#*=}" ;;
@@ -49,7 +51,7 @@ while [ "$#" -gt 0 ]; do
 			elif [ "$repo" = "" ]; then
 				repo="$1"
 			else
-				echo ! Invalid command line flag $1. >&2; 
+				echo "! Invalid command line flag $1." >&2; 
 				exit 1
 			fi
 			;;
@@ -57,7 +59,7 @@ while [ "$#" -gt 0 ]; do
 	shift
 done
 
-test $verbose && set -x
+test -n "$verbose" && set -x
 set -e
 
 lookupdir="share"
@@ -71,44 +73,47 @@ if [ ! -d "$path/$lookupdir" ]; then
 fi
 
 if [ "$command" = "ls" ]; then
-	ls -1 "$path/$lookupdir/" | sed 's/,,/ -b=/' | tr , /
-	exit 0
+	find "$path/$lookupdir" -type l -execdir echo {} \; | sed 's/,,/ -b=/' | tr , /
+	exit
+elif [ "$command" = "up-all" ]; then
+	"$0" ls | xargs -L1 "$0" up
+	exit
 fi
 
-test ! "$repo" = "" || { echo ! Missing repo. >&2; exit 1; } 
+test -n "$repo" || { echo ! Missing repo. >&2; exit 1; } 
 test "$repo" = "${repo% *}" || { echo ! Cannot have spaces in repo. >&2; exit 1; }
 subpath="$repo"
 subpath="${subpath#*//}" # remove ^https://
 subpath="${subpath#*@}" # remove ^git@
 subpath="${subpath%.git}" # remove .git$
-subpath=$(printf "$subpath" | tr : /) # replace : with /
-test ! "$(printf "$subpath" | tr -d / | tr -d '.')" = "" || { echo ! Local subpath results in empty or invalid path. >&2; exit 1; } 
+subpath=$(printf '%s' "$subpath" | tr : /) # replace : with /
+test ! "$(printf '%s' "$subpath" | tr -d / | tr -d '.')" = "" || { echo ! Local subpath results in empty or invalid path. >&2; exit 1; } 
 if [ "$branch" = "" ]; then
-	branch="$(git ls-remote --tags --sort="v:refname" https://$subpath.git | tail -n1 | awk -F '[/\^]' '{print $3}')"  # get latest tag
-	test ! "$branch" = "" || branch="$(git ls-remote --symref https://$subpath.git HEAD | awk '/^ref:/ {sub(/refs\/heads\//, "", $2); print $2}')" # or get default branch
-	link="$path/$lookupdir/$(printf "$subpath" | tr / ,)" # will not include branch/tag for rolling release
+	branch="$(git ls-remote --tags --sort="v:refname" "https://$subpath.git" | tail -n1 | awk -F '[/\^]' '{print $3}')"  # get latest tag
+	test ! "$branch" = "" || branch="$(git ls-remote --symref "https://$subpath.git" HEAD | awk '/^ref:/ {sub(/refs\/heads\//, "", $2); print $2}')" # or get default branch
+	link="$path/$lookupdir/$(printf '%s' "$subpath" | tr / ,)" # will not include branch/tag for rolling release
 else
-	link="$path/$lookupdir/$(printf "$subpath,,$branch" | tr / ,)"
+	link="$path/$lookupdir/$(printf "%s,,%s" "$subpath" "$branch" | tr / ,)"
 fi
 fullpath="$path/$subpath/$branch"
 
 if [ "$command" = "dir" ]; then
 	test -d "$link" || exit 2
-	echo "$(readlink -f "$link")" && exit 0
+	readlink -f "$link" && exit 0
 elif [ "$command" = "sh" ]; then
 	test -d "$link" || { echo ! Repository doesn\'t exist on the local system. >&2; exit 2; }
 	cd "$path/$lookupdir/$(readlink "$link")"
 	"$SHELL" -i && exit 0
 elif [ "$command" = "add" ]; then
-	if [ $force ]; then
+	if [ -n "$force" ]; then
 		rm -rf "$fullpath" || true
 		rm -rf "$link" || true
 	fi
 	test ! -d "$link" || { echo ! Repository already added to the local system, consider updating it using the up-command instead or add the -f flag to forcefully re-install. >&2; exit 2; }
-	echo - Adding $repo \($branch\) to $fullpath ...
+	echo "- Adding $repo \($branch\) to $fullpath ..."
 	if [ ! -d "$fullpath" ]; then
 		mkdir -p "$fullpath"
-		git clone --recursive --depth 1 --branch $branch $repo "$fullpath"
+		git clone --recursive --depth 1 --branch "$branch" "$repo" "$fullpath"
 	else
 		echo - Repository already found, version link will be added ...
 	fi
@@ -116,17 +121,17 @@ elif [ "$command" = "add" ]; then
 elif [ "$command" = "up" ]; then
 	test -d "$link" || { echo ! Repository doesn\'t exist on the local system. >&2; exit 2; }
 	# TODO: Detect if on a tag at the moment. If so, check if there is a new tag. If so, update to new tag.
-	echo - Updating $fullpath ...
+	echo - Updating "$fullpath" ...
 	if [ ! -d "$fullpath" ]; then # link exists but determined fullpath does not?
-		rm -rf "$path/$lookupdir/$(readlink $link)" || true # try to remove old version
-		rm $link
+		rm -rf "${path:?}/$lookupdir/$(readlink "$link")" || true # try to remove old version
+		rm "$link"
 		# TODO: don't delete old version if it is installed seperately
 		mkdir -p "$fullpath"
-		git clone --recursive --depth 1 --branch $branch $repo "$fullpath"
+		git clone --recursive --depth 1 --branch "$branch" "$repo" "$fullpath"
 		ln -sf "../$subpath/$branch" "$link"
 	else
 		if ! git -C "$fullpath" pull --rebase; then
-			if [ $force ]; then
+			if [ "$force" ]; then
 				git -C "$fullpath" reset --hard
 				git -C "$fullpath" pull --ff-only
 			else
@@ -137,17 +142,17 @@ elif [ "$command" = "up" ]; then
 		fi
 	fi
 elif [ "$command" = "del" ]; then
-	test -d "$link" || test $force || { echo ! Repository doesn\'t exist on the local system. Use the -f flag to forcefully try delete and clean up anyways. >&2; exit 2; }
-	test -d "$link" && fullpath="$path$(readlink $link | sed 's/^..//')" # get real fullpath in case of older rolling
-	echo - Deleting $fullpath ...
-	rm -rf "$fullpath" || test $force
+	test -d "$link" || test -n "$force" || { echo ! Repository doesn\'t exist on the local system. Use the -f flag to forcefully try delete and clean up anyways. >&2; exit 2; }
+	test -d "$link" && fullpath="$path$(readlink "$link" | sed 's/^..//')" # get real fullpath in case of older rolling
+	echo "- Deleting $fullpath ..."
+	rm -rf "$fullpath" || test -n "$force"
 	echo - Cleaning up ...
-	rm -rf "$link" || test $force
+	rm -rf "$link" || test -n "$force"
 	rmdir "$path/$lookupdir" 2>/dev/null || true
 	find "$path/" -depth -mindepth 1 -type d -exec rmdir {} + 2>/dev/null || true
 	# TODO: Tackle invisible files
 else
-	echo ! Unknown command $command. >&2 
+	echo "! Unknown command $command." >&2 
 	exit 1 
 fi
 
