feat: extensible sys-backup / sys-upgrade

diff --git a/bin/sys-backup b/bin/sys-backup
--- a/bin/sys-backup
+++ b/bin/sys-backup
@@ -14,6 +14,7 @@ OPTIONS
   -p=*, --path=*                  Sets the path to the backup directory if possible (default: $HOME/.sys-backup). Ignored on MacOS.
   -m=*, --max-size=*              Sets the maximum size of every backup-ed file (default: 10M). Ignored on MacOS.
   -k,   --keep-files              Keeps the old backup files that are not overwritten. Ignored on MacOS.
+  -x,   --extensive               Also runs extensions (*.sh files) within \$XDG_CONFIG_HOME/mbx/sys-backup/extensions and \$XDG_CONFIG_DIRS/mbx/sys-backup/extensions.
   -l,   --lock-backup             Locks the backup by rejecting access permissions to the current user. Ignored on MacOS.
   -s,   --shutdown                Shutdowns the system 5 minutes after successful system backup.
   -h,   --help                    Prints this help message.
@@ -79,6 +80,29 @@ if test-command sudo; then
 else
 	rsync $opts --delete --max-size=$max_size "${excl[@]}" / "$path"
 	(( $keep_files )) || find "$path" -type f -size +$max_size -delete
+fi
+
+if [ $extensive ]; then
+	extsubpath="mbx/sys-backup/extensions"
+	extdir="$XDG_CONFIG_HOME/$extsubpath" 
+	if [ -d "$extdir" ]; then
+		extfiles=( $(find "$extdir" -mindepth 1 -maxdepth 1 -type f -name '*.sh') )
+		for f in "${extfiles[@]}"; do
+			# echo $f
+			[ -f "$f" ] && { . "$f" || { echo "[!] Failed to source $f" && exit 1; }; }
+		done 
+	fi
+	( IFS=: 
+	for confdir in $XDG_CONFIG_DIRS; do
+		extdir="$confdir/$extsubpath"
+		if [ -d "$extdir" ]; then
+			extfiles=( $(find "$extdir" -mindepth 1 -maxdepth 1 -type f -name '*.sh') )
+			for f in "${extfiles[@]}"; do
+				# echo $f
+				[ -f "$f" ] && { . "$f" || { echo "[!] Failed to source $f" && exit 1; }; }
+			done 
+		fi
+	done; )
 fi
 
 if [ $lock_backup ]; then
diff --git a/bin/sys-upgrade b/bin/sys-upgrade
--- a/bin/sys-upgrade
+++ b/bin/sys-upgrade
@@ -17,6 +17,7 @@ Upgrades all packages of all supported package managers. Supports:
 OPTIONS
   -V,   --version                 Prints the version of this script suite (MBX).
   -v,   --verbose                 Prints verbose information.
+  -x,   --extensive               Also runs extensions (*.sh files) within \$XDG_CONFIG_HOME/mbx/sys-upgrade/extensions and \$XDG_CONFIG_DIRS/mbx/sys-upgrade/extensions.
   -r,   --reboot                  Reboots the system after successful upgrade.
   -h,   --help                    Prints this help message.
 EOF
@@ -25,6 +26,7 @@ while [ "$#" -gt 0 ]; do
 	case "$1" in
 		-V|--version) echo $MBX_VERSION && exit 0 ;;
 		-v|--verbose) verbose=1 ;;
+		-x|--extensive) extensive=1 ;;
 		-r|--reboot) reboot=1 ;;
 		-h|--help) echo "$usage" && exit 0 ;;
 		*) echo "[x] Invalid command line flag $1." >&2; exit 1 ;;
@@ -77,13 +79,10 @@ fi
 
 if test-command gem; then
 	if test-command rbenv; then
-
 		current_ruby_version=$(rbenv global)
 		installed_ruby_versions=($(rbenv versions | awk -F "[ ]+" '/ /{print $2}'))
 		available_ruby_versions=($(rbenv install -l 2>/dev/null))
-
 		echo "[o] Updating Ruby builds ..."
-
 		for installed in "${installed_ruby_versions[@]}"; do
 			if [ "$installed" = "system" ]; then
 				continue
@@ -97,29 +96,26 @@ if test-command gem; then
 					= \
 					"$(echo $available | tr '.' '\n' | head -2)" \
 					]; then
-					rbenv install $available
-					# TODO: Install all global packages from $installed to $available
-					if [ "$current_ruby_version" = "$installed" ]; then
-						rbenv global $available
-					fi
-					if test-command sudo; then
-						sudo rbenv uninstall -f $installed
-					else
-						rbenv uninstall -f $installed
-					fi
+									rbenv install $available
+									# TODO: Install all global packages from $installed to $available
+									if [ "$current_ruby_version" = "$installed" ]; then
+										rbenv global $available
+									fi
+									if test-command sudo; then
+										sudo rbenv uninstall -f $installed
+									else
+										rbenv uninstall -f $installed
+									fi
 				fi
 			done
 		done
-
 	fi
-
 	echo "[o] Upgrading global Ruby gems ..."
 	if test-command sudo; then
 		sudo gem update --system
 	else
 		gem update --system
 	fi
-
 fi
 
 if [ -s "$HOME/.nvm/nvm.sh" ]; then
@@ -191,6 +187,29 @@ elif test-command flutter; then
 	echo "[o] Upgrading Flutter ..."
 	flutter upgrade
 	dart pub global activate rps
+fi
+
+if [ $extensive ]; then
+	extsubpath="mbx/sys-upgrade/extensions"
+	extdir="$XDG_CONFIG_HOME/$extsubpath" 
+	if [ -d "$extdir" ]; then
+		extfiles=( $(find "$extdir" -mindepth 1 -maxdepth 1 -type f -name '*.sh') )
+		for f in "${extfiles[@]}"; do
+			# echo $f
+			[ -f "$f" ] && { . "$f" || { echo "[!] Failed to source $f" && exit 1; }; }
+		done 
+	fi
+	( IFS=: 
+	for confdir in $XDG_CONFIG_DIRS; do
+		extdir="$confdir/$extsubpath"
+		if [ -d "$extdir" ]; then
+			extfiles=( $(find "$extdir" -mindepth 1 -maxdepth 1 -type f -name '*.sh') )
+			for f in "${extfiles[@]}"; do
+				# echo $f
+				[ -f "$f" ] && { . "$f" || { echo "[!] Failed to source $f" && exit 1; }; }
+			done 
+		fi
+	done; )
 fi
 
 if [ $reboot ]; then
